-- =========================================================================
-- KỊCH BẢN KHOẢNG KHỞI TẠO DỮ LIỆU SUPABASE POSTGRESQL THCS ĐỒNG TÂN (AN TOÀN 100%)
-- Sao chép toàn bộ mã SQL dưới đây và dán vào Supabase Dashboard: SQL Editor -> Run
-- =========================================================================

-- -------------------------------------------------------------------------
-- PHẦN 1: TẠO TẤT CẢ CÁC BẢNG DỮ LIỆU (CREATE TABLES FIRST)
-- -------------------------------------------------------------------------

-- 1. BẢNG NGƯỜI DÙNG & THÀNH VIÊN (users)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'GIAO_VIEN',
  email TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BẢNG CHUYÊN MỤC TIN TỨC (categories)
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  icon TEXT DEFAULT 'Newspaper',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BẢNG BÀI VIẾT TIN TỨC & SỰ KIỆN (articles)
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  category_name TEXT DEFAULT 'Tin tức - Sự kiện',
  summary TEXT DEFAULT '',
  content TEXT DEFAULT '',
  image TEXT DEFAULT '',
  file_url TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  author TEXT DEFAULT 'Ban Biên Tập THCS Đồng Tân',
  is_featured INT DEFAULT 0,
  views INT DEFAULT 120,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BẢNG VĂN BẢN CHỈ ĐẠO & QUY CHẾ (documents)
CREATE TABLE IF NOT EXISTS public.documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Thông tư BGD&ĐT',
  issue_date TEXT NOT NULL,
  signer TEXT DEFAULT 'THCS Đồng Tân',
  file_url TEXT DEFAULT '',
  file_name TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  views INT DEFAULT 4500,
  downloads INT DEFAULT 1700,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. BẢNG THƯ VIỆN VIDEO (videos)
CREATE TABLE IF NOT EXISTS public.videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  youtube_id TEXT DEFAULT '',
  thumbnail_url TEXT DEFAULT '',
  video_url TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  views INT DEFAULT 890,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. BẢNG THƯ VIỆN ALBUMS ẢNH (albums)
CREATE TABLE IF NOT EXISTS public.albums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT DEFAULT '08/08/2026',
  photos_count INT DEFAULT 10,
  cover TEXT DEFAULT '',
  description TEXT DEFAULT '',
  file_url TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. BẢNG KHO TÀI NGUYÊN & ĐỀ THI (resources)
CREATE TABLE IF NOT EXISTS public.resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT DEFAULT 'Đề thi & Đáp án',
  subject TEXT DEFAULT 'Toán 9',
  author TEXT DEFAULT 'Tổ Chuyên Môn',
  date TEXT DEFAULT '08/08/2026',
  downloads INT DEFAULT 450,
  file_url TEXT DEFAULT '',
  file_name TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. BẢNG LỊCH CÔNG TÁC TUẦN (schedules)
CREATE TABLE IF NOT EXISTS public.schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_title TEXT NOT NULL,
  time_slot TEXT NOT NULL,
  content TEXT NOT NULL,
  leader TEXT DEFAULT 'Ban Giám Hiệu',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. BẢNG THÔNG BÁO CHỮ CHẠY (announcements)
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  link TEXT DEFAULT '',
  priority INT DEFAULT 1,
  is_active INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. BẢNG CẤU HÌNH TRƯỜNG HỌC & BANNER (site_config)
CREATE TABLE IF NOT EXISTS public.site_config (
  id INT PRIMARY KEY DEFAULT 1,
  school_name TEXT DEFAULT 'TRƯỜNG THCS ĐỒNG TÂN',
  governing_body TEXT DEFAULT 'ỦY BAN NHÂN DÂN XÃ HỮU LŨNG - TỈNH LẠNG SƠN',
  slogan TEXT DEFAULT 'HỘI TỤ - KẾT TINH - TỎA SÁNG',
  address TEXT DEFAULT 'Xã Hữu Lũng - Tỉnh Lạng Sơn',
  phone TEXT DEFAULT '(0205) 3885.6789',
  email TEXT DEFAULT 'thcsdongtan.huulung@langson.edu.vn',
  logo_url TEXT DEFAULT '/images/school-logo.jpg',
  banner_bg TEXT DEFAULT '/images/school-banner.png',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. BẢNG LIÊN KẾT NHANH (quick_links)
CREATE TABLE IF NOT EXISTS public.quick_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  target TEXT DEFAULT '_blank',
  position TEXT DEFAULT 'footer',
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- PHẦN 1.5: TỰ ĐỘNG BỔ SUNG CỘT CÒN THIẾU VÀ GỠ BỎ CHECK CONSTRAINTS CŨ GÂY LỖI
-- -------------------------------------------------------------------------

-- Gỡ bỏ tất cả các check constraints cũ trên bảng users có thể gây xung đột giá trị role/status
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS users_status_check;
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS role_check;
ALTER TABLE public.users DROP CONSTRAINT IF EXISTS status_check;

-- Gỡ bỏ các check constraints trên các bảng khác nếu có
ALTER TABLE public.articles DROP CONSTRAINT IF EXISTS articles_is_featured_check;
ALTER TABLE public.quick_links DROP CONSTRAINT IF EXISTS quick_links_position_check;

ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS icon TEXT DEFAULT 'Newspaper';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'ACTIVE';
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS file_url TEXT DEFAULT '';
ALTER TABLE public.articles ADD COLUMN IF NOT EXISTS external_link TEXT DEFAULT '';
ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS file_name TEXT DEFAULT '';
ALTER TABLE public.documents ADD COLUMN IF NOT EXISTS external_link TEXT DEFAULT '';
ALTER TABLE public.videos ADD COLUMN IF NOT EXISTS video_url TEXT DEFAULT '';
ALTER TABLE public.videos ADD COLUMN IF NOT EXISTS external_link TEXT DEFAULT '';
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS file_url TEXT DEFAULT '';
ALTER TABLE public.albums ADD COLUMN IF NOT EXISTS external_link TEXT DEFAULT '';
ALTER TABLE public.resources ADD COLUMN IF NOT EXISTS file_name TEXT DEFAULT '';
ALTER TABLE public.resources ADD COLUMN IF NOT EXISTS external_link TEXT DEFAULT '';

ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS principal_name TEXT DEFAULT 'Thầy Hiệu Trưởng - THCS Đồng Tân';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS principal_title TEXT DEFAULT 'Hiệu Trưởng Nhà Trường';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS principal_avatar TEXT DEFAULT 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS vice_principal1_name TEXT DEFAULT 'Cô Phó Hiệu Trưởng - THCS Đồng Tân';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS vice_principal1_title TEXT DEFAULT 'Phó Hiệu Trưởng Chuyên Môn';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS vice_principal1_avatar TEXT DEFAULT 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS vice_principal2_name TEXT DEFAULT 'Thầy Phó Hiệu Trưởng - CSVC';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS vice_principal2_title TEXT DEFAULT 'Phó Hiệu Trưởng Cơ Sở Vật Chất';
ALTER TABLE public.site_config ADD COLUMN IF NOT EXISTS vice_principal2_avatar TEXT DEFAULT 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&q=80';

-- Cập nhật mặc định cho status nếu giá trị đang là NULL hoặc APPROVED
UPDATE public.users SET status = 'ACTIVE' WHERE status IS NULL OR status = 'APPROVED';
UPDATE public.users SET role = 'BGH' WHERE role = 'ADMIN';
UPDATE public.users SET role = 'GIAO_VIEN' WHERE role = 'TEACHER';
UPDATE public.users SET role = 'HOC_SINH' WHERE role = 'STUDENT';
UPDATE public.users SET role = 'PHU_HUYNH' WHERE role = 'PARENT';

-- Làm sạch các đường dẫn ảnh bìa không hợp lệ trong bảng albums và articles
UPDATE public.albums 
SET cover = 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&q=80'
WHERE cover IS NULL OR cover = '' OR (cover NOT LIKE 'http%' AND cover NOT LIKE 'data:%');

UPDATE public.articles 
SET image = 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&q=80'
WHERE image IS NULL OR image = '' OR (image NOT LIKE 'http%' AND image NOT LIKE 'data:%');

-- Cập nhật mật khẩu mặc định/mới cho tài khoản admin
UPDATE public.users SET password = 'admindt' WHERE username = 'admin';

-- -------------------------------------------------------------------------
-- PHẦN 2: BẬT BẢO MẬT ROW LEVEL SECURITY (KHI BẢNG ĐÃ TỒN TẠI)
-- -------------------------------------------------------------------------

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quick_links ENABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------------------
-- PHẦN 3: XÓA VÀ TẠO CÁC POLICY PHÂN QUYỀN TRUY CẬP AN TOÀN
-- -------------------------------------------------------------------------

DROP POLICY IF EXISTS "Public Select Users" ON public.users;
DROP POLICY IF EXISTS "Public Select Categories" ON public.categories;
DROP POLICY IF EXISTS "Public Select Articles" ON public.articles;
DROP POLICY IF EXISTS "Public Select Documents" ON public.documents;
DROP POLICY IF EXISTS "Public Select Videos" ON public.videos;
DROP POLICY IF EXISTS "Public Select Albums" ON public.albums;
DROP POLICY IF EXISTS "Public Select Resources" ON public.resources;
DROP POLICY IF EXISTS "Public Select Schedules" ON public.schedules;
DROP POLICY IF EXISTS "Public Select Announcements" ON public.announcements;
DROP POLICY IF EXISTS "Public Select SiteConfig" ON public.site_config;
DROP POLICY IF EXISTS "Public Select QuickLinks" ON public.quick_links;

DROP POLICY IF EXISTS "Public All Users" ON public.users;
DROP POLICY IF EXISTS "Public All Articles" ON public.articles;
DROP POLICY IF EXISTS "Public All Documents" ON public.documents;
DROP POLICY IF EXISTS "Public All Videos" ON public.videos;
DROP POLICY IF EXISTS "Public All Albums" ON public.albums;
DROP POLICY IF EXISTS "Public All Resources" ON public.resources;
DROP POLICY IF EXISTS "Public All Schedules" ON public.schedules;
DROP POLICY IF EXISTS "Public All SiteConfig" ON public.site_config;
DROP POLICY IF EXISTS "Public All QuickLinks" ON public.quick_links;

DROP POLICY IF EXISTS "Public Select All" ON public.articles;
DROP POLICY IF EXISTS "Public Select Docs" ON public.documents;
DROP POLICY IF EXISTS "Public Select Config" ON public.site_config;

-- Tạo các Policy mới
CREATE POLICY "Public Select Users" ON public.users FOR SELECT USING (true);
CREATE POLICY "Public Select Categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Public Select Articles" ON public.articles FOR SELECT USING (true);
CREATE POLICY "Public Select Documents" ON public.documents FOR SELECT USING (true);
CREATE POLICY "Public Select Videos" ON public.videos FOR SELECT USING (true);
CREATE POLICY "Public Select Albums" ON public.albums FOR SELECT USING (true);
CREATE POLICY "Public Select Resources" ON public.resources FOR SELECT USING (true);
CREATE POLICY "Public Select Schedules" ON public.schedules FOR SELECT USING (true);
CREATE POLICY "Public Select Announcements" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "Public Select SiteConfig" ON public.site_config FOR SELECT USING (true);
CREATE POLICY "Public Select QuickLinks" ON public.quick_links FOR SELECT USING (true);

CREATE POLICY "Public All Users" ON public.users FOR ALL USING (true);
CREATE POLICY "Public All Articles" ON public.articles FOR ALL USING (true);
CREATE POLICY "Public All Documents" ON public.documents FOR ALL USING (true);
CREATE POLICY "Public All Videos" ON public.videos FOR ALL USING (true);
CREATE POLICY "Public All Albums" ON public.albums FOR ALL USING (true);
CREATE POLICY "Public All Resources" ON public.resources FOR ALL USING (true);
CREATE POLICY "Public All Schedules" ON public.schedules FOR ALL USING (true);
CREATE POLICY "Public All SiteConfig" ON public.site_config FOR ALL USING (true);
CREATE POLICY "Public All QuickLinks" ON public.quick_links FOR ALL USING (true);

-- -------------------------------------------------------------------------
-- PHẦN 4: NẠP DỮ LIỆU MẪU BAN ĐẦU (SEED DATA - AN TOÀN TRÁNH TRÙNG KHÓA)
-- -------------------------------------------------------------------------

INSERT INTO public.categories (id, name, slug, icon) VALUES
(1, 'Tin tức - Sự kiện', 'tin-tuc-su-kien', 'Newspaper'),
(2, 'Hoạt động chuyên môn', 'hoat-dong-chuyen-mon', 'BookOpen'),
(3, 'Hoạt động đoàn thể', 'hoat-dong-doan-the', 'Users'),
(4, 'Hoạt động ngoại khóa', 'hoat-dong-ngoai-khoa', 'Sparkles'),
(5, 'Câu lạc bộ', 'cau-lac-bo', 'Trophy')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.users (id, username, password, full_name, role, email, status) VALUES
(1, 'admin', 'admindt', 'Thầy Hiệu Trưởng - THCS Đồng Tân', 'BGH', 'bgh.thcsdongtan@langson.edu.vn', 'ACTIVE'),
(2, 'giaovien', '$2a$10$84J.N1i1JvCjJmI/K2D/Me1M.Kx7XG1t3VnS3bK7V9tL.u8.k1u.', 'Cô Nguyễn Thị Hoa - Giáo Viên Văn', 'GIAO_VIEN', 'hoanguyen@thcsdongtan.edu.vn', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.users (username, password, full_name, role, email, status) VALUES
('hocsinh01', '$2a$10$84J.N1i1JvCjJmI/K2D/Me1M.Kx7XG1t3VnS3bK7V9tL.u8.k1u.', 'Em Nguyễn Văn An - Học sinh 9A1', 'HOC_SINH', 'an.nguyen@thcsdongtan.edu.vn', 'ACTIVE'),
('phuhuynh01', '$2a$10$84J.N1i1JvCjJmI/K2D/Me1M.Kx7XG1t3VnS3bK7V9tL.u8.k1u.', 'Anh Trần Văn Bình (Phụ huynh 9A)', 'PHU_HUYNH', 'binhtran@gmail.com', 'ACTIVE'),
('giaovien_toan', '$2a$10$84J.N1i1JvCjJmI/K2D/Me1M.Kx7XG1t3VnS3bK7V9tL.u8.k1u.', 'Cô Lê Thị Thu - Giáo viên Toán', 'GIAO_VIEN', 'thule@thcsdongtan.edu.vn', 'ACTIVE')
ON CONFLICT (username) DO NOTHING;

INSERT INTO public.site_config (id, school_name, governing_body, slogan, address, phone, email, logo_url, banner_bg) VALUES
(1, 'TRƯỜNG THCS ĐỒNG TÂN', 'ỦY BAN NHÂN DÂN XÃ HỮU LŨNG - TỈNH LẠNG SƠN', 'HỘI TỤ - KẾT TINH - TỎA SÁNG', 'Xã Hữu Lũng - Tỉnh Lạng Sơn', '(0205) 3885.6789', 'thcsdongtan.huulung@langson.edu.vn', '/images/school-logo.jpg', '/images/school-banner.png')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.quick_links (id, title, url, target, position, sort_order) VALUES
(1, 'Giới thiệu nhà trường', '#intro', '_self', 'footer', 1),
(2, 'Tin tức - Sự kiện nổi bật', '#news', '_self', 'footer', 2),
(3, 'Văn bản chỉ đạo & Quy chế', '#docs', '_self', 'footer', 3),
(4, 'Kho Tài nguyên & Đề thi', '#resources', '_self', 'footer', 4),
(5, 'Lịch công tác tuần', '#schedule', '_self', 'footer', 5),
(6, 'Bộ Giáo Dục & Đào Tạo', 'http://moet.gov.vn', '_blank', 'sidebar', 6),
(7, 'Sở GD&ĐT Tỉnh Lạng Sơn', 'https://langson.edu.vn', '_blank', 'sidebar', 7),
(8, 'UBND Xã Hữu Lũng', 'https://huulung.langson.gov.vn', '_blank', 'sidebar', 8)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.articles (id, title, slug, category_id, category_name, summary, content, image, author, is_featured, views) VALUES
(1, 'Lễ kết nạp Đảng viên mới cho cán bộ giáo viên THCS Đồng Tân', 'le-ket-nap-dang-vien-moi', 1, 'Tin tức - Sự kiện', 'Vào lúc 14 giờ 00, Chi bộ trường THCS Đồng Tân đã long trọng tổ chức Lễ kết nạp Đảng viên cho giáo viên ưu tú có nhiều thành tích xuất sắc.', 'Chiều ngày 04/08/2026, Chi bộ Trường THCS Đồng Tân đã tiến hành Lễ kết nạp Đảng viên cho quần chúng ưu tú.', 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&q=80', 'Ban Biên Tập THCS Đồng Tân', 1, 1250)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.documents (id, code, title, category, issue_date, signer, views, downloads) VALUES
(1, 'TT07/2026/TT-BGDĐT', 'Thông tư 07/2026/TT-BGDĐT về Phổ cập giáo dục THCS và Xóa mù chữ năm 2026', 'Thông tư BGD&ĐT', '04/08/2026', 'Bộ trưởng BGD&ĐT', 4830, 1722),
(2, 'TT42/2025/TT-BGDĐT', 'Quy chế công nhận trường Trung học đạt chuẩn quốc gia cấp độ 2', 'Quy chế Nhà trường', '15/12/2025', 'Thứ trưởng BGD&ĐT', 3410, 1205)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.videos (id, title, youtube_id, thumbnail_url, views) VALUES
(1, 'Phim tư liệu: 40 năm truyền thống Dạy tốt - Học tốt THCS Đồng Tân', 'k8F4q_N-g_w', 'https://images.unsplash.com/photo-1577896851231-70ef18881754?w=600&q=80', 1540)
ON CONFLICT (id) DO NOTHING;
